name: Автоматическое исправление стиля кода

on:
  # Запускается вручную из интерфейса GitHub
  workflow_dispatch:
  # Запускается по расписанию (каждую неделю в понедельник в 00:00 UTC)
  schedule:
    - cron: '0 0 * * 1'

jobs:
  auto-fix:
    name: Исправление ESLint и Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Полная история для правильной работы с git
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fix code formatting with Prettier
        run: npm run format

      - name: Fix code with ESLint
        run: npm run lint:fix

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "style: автоматическое исправление стиля кода"

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "style: автоматическое исправление стиля кода"
          body: |
            Этот PR был создан автоматически для исправления стиля кода.

            Изменения включают:
            - Форматирование кода с помощью Prettier
            - Исправление проблем ESLint
          branch: auto-fix-code-style
          delete-branch: true
          labels: |
            automated pr
            style
